[shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "alacritty"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.85

[font]
normal.family = "Inconsolata Nerd Font"
bold.family = "Inconsolata Nerd Font"
italic.family = "Inconsolata Nerd Font"
bold_italic.family = "Inconsolata Nerd Font"
size = 15

[colors]
# Default colors
[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

# Normal colors
[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

# Bright colors
[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"


